# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support

sudo: required
dist: bionic

os: linux
language: generic

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

env:
  global:
    # DOCKER_HUB_USER
    - secure: "absolutetestuser"
    # DOCKER_HUB_PASSWORD
    - secure: "absolutetestuser"
    - DOCKER_BUILD=false

stages:
  - build depends
  - build src
  - run tests
  - build docker

builddepends: &builddepends
  stage: build depends
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh

buildsrc: &buildsrc
  stage: build src
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh

runtests: &runtests
  stage: run tests
  script:
    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/test_unittests.sh
    - $DOCKER_RUN_IN_BUILDER ./ci/test_integrationtests.sh --jobs=3

builddocker: &builddocker
  stage: build docker
  script:
    # no need to run tests again here
    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh && BUILD_DIR=build-ci/absolutecore-$BUILD_TARGET ./docker/build-docker.sh; fi

jobs:
  include:
    # build depends
    - <<: *builddepends
      env: BUILD_TARGET=arm-linux
    - <<: *builddepends
      env: BUILD_TARGET=win64
    - <<: *builddepends
      env: BUILD_TARGET=linux64
    - <<: *builddepends
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    - <<: *builddepends
      env: BUILD_TARGET=mac
    # build source
    - <<: *buildsrc
      env: BUILD_TARGET=arm-linux
    - <<: *buildsrc
      env: BUILD_TARGET=win64
    - <<: *buildsrc
      env: BUILD_TARGET=linux64
    - <<: *buildsrc
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    - <<: *buildsrc
      env: BUILD_TARGET=mac
    # run tests (no tests for arm-linux and mac)
    - <<: *runtests
      env: BUILD_TARGET=win64
    - <<: *runtests
      env: BUILD_TARGET=linux64
    - <<: *runtests
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
    # build docker
    - <<: *builddocker
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true

before_cache:
  # Save builder image
  - docker save absolute-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q absolute-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/absolute-builder-$BUILD_TARGET.tar.gz

before_install:
  - travis_retry travis_apt_get_update
  - travis_retry sudo apt-get -yq --no-install-suggests --no-install-recommends install docker-ce

install:
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
    - export HOST_CACHE_DIR=$HOME/cache
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - source ./ci/matrix.sh
    - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
    # Keep this as it makes caching related debugging easier
    - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
    # Load cached builder image
    - if [ -f $HOST_CACHE_DIR/docker/absolute-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/absolute-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - travis_retry docker pull ubuntu:bionic
    - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then (echo "Upload goes here. Something like: scp -r $BASE_OUTDIR server" || echo "upload failed"); fi
